### ISSUE TITLE
Proxy UI RPC information is not intuitively shown to viewers

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/skale-proxy#8]
> As a developer, when I load the proxy UI I am not aware of hidden RPC information for each SKALE chain name.

Help the viewer understand that each item is expandable on page load.

**Comment by cstrangedk** [comment]
@PolinaKiporenko to recommend zero-state suggestions for guiding user to expandable info sections.

**Comment by PolinaKiporenko** [comment]
@cstrangedk @dmitry-tk 
Suggestion for UI:
- add search bar in the top of SKALEchains list (as the number of  SKALEchains will increase and it will be difficult to find the right one)
- to make the RPC endpoints more explicit, replace the "expand arrow" with the button "Get endpoints" 
- maybe it would be good to add Metamask and Block-explorer icons to the top level next to the SKALEchain name - so that the user can see the available functionality at once 
<img width="1377" alt="Proxy" src="https://user-images.githubusercontent.com/101632617/182227424-6a90bb55-eac2-456e-955a-9cf0ce7a948d.png">

**Comment by cstrangedk** [comment]
@dmitry-tk need the "get endpoints" button for the next hackathon

**Comment by dmytrotkk** [comment]
Intermediate solution:
<img width="1511" alt="Screenshot 2022-08-02 at 18 46 33" src="https://user-images.githubusercontent.com/15244591/182440263-526f5103-dad6-461e-a4f5-760bde06fd0c.png">

Though I don't think we need 'Get endpoints' buttons in the new Network UI. 

CC: @cstrangedk

**Comment by dmytrotkk** [comment]
@cstrangedk can we close this one?

**Comment by PolinaKiporenko** [comment]
After discussion with @cstrangedk decided that it's clear for users in the new Network UI where click to get all info about chain, so, we can close the issue
